name: build default on ubuntu clang

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 */2 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install cmake make clang ccache wget tar

      - name: install environment
        run: |
          wget https://github.com/openbfdev/bfdev/releases/download/nightly/bfdev-linux-amd64.tar.gz
          sudo tar -xzvf bfdev-linux-amd64.tar.gz -C /usr

      - name: configure cmake
        run: |
          cmake -B ${{github.workspace}}/build \
                -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install \
                -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -D CMAKE_C_COMPILER=/usr/lib/ccache/clang

      - name: make
        run: |
          cmake --build ${{github.workspace}}/build \
                --config ${{env.BUILD_TYPE}}

      - name: install
        run: |
          cmake --build ${{github.workspace}}/build \
                --config ${{env.BUILD_TYPE}} -- install

      - name: ctest
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -V
